language: cpp
sudo: required
os:
  - linux
  - osx
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - export CXX=g++-4.8
  - make all
  - make test
