language: cpp
sudo: required
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - export CXX=g++-4.8
  - export GCC_LOCATION="$(which g++)"
  - sudo rm -rf "${GCC_LOCATION}"
  - sudo mv "$(which g++-4.8)" "${GCC_LOCATION}"
  - make all
  - make test
